--- 
title: "Data Science for Physicians (DS4P)"
author: "Peter Higgins"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
output: 
  bookdown::gitbook: 
    highlight: tango
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is an introduction to Data Science targeted at Physicians. The output format for this example is bookdown::gitbook."
---

# Prerequisites

Thank you for giving this e-book a try. This is designed for physicians or others analyzing health data who are interested in pursuing this field using the R language.
<br>
We will assume that:

- you have access to a computer
- that you have access to the internet
- that you can download the current version of R, and 
- that you have downloaded a current version of Rstudio.
<br>

### To Install R:

- Open an internet browser and go to <https://www.r-project.org>.
- Click the "download R" link in the middle of the page under "Getting Started."
- Select a CRAN location (a mirror site) and click the corresponding link.  
- Click on the "Download R for Windows" link at the top of the page.  
- Click on the "install R for the first time" link at the top of the page.
- Click "Download R for Windows" and save the executable file somewhere on your computer.  Run the .exe file and follow the installation instructions.  
- Now that R is installed, you need to download and install RStudio. <br>

### To Install RStudio:

- Go to <http://www.rstudio.com> and click on the "Download RStudio" button.
- Click on "Download RStudio Desktop."
- Click on the version recommended for your system (Windows, Mac, Linux), and save the downloaded file.  Run the file and follow the installation instructions.     
<br>
<br>
<br>
<br>

This is a book written in **RMarkdown**. 

Each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. It is recommended that you install the TinyTeX package (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
